version: "3.9"
services:
  #frontend:
  #  build: ./frontend
  #  container_name: frontend
  #  ports:
  #    - "5173:5173"
  #  env_file:
  #    - ./frontend/.env
  #  environment:
  #    - VITE_API_URL=http://localhost:8080
  #  volumes:
  #    - ./frontend:/app
  #    - /app/node_modules
  #  command: npm run dev -- --host
  #  depends_on:
  #    - backend

  # backend:
  #   build: ./backend
  #   container_name: backend
  #   ports:
  #     - "8080:8080"
  #   env_file:
  #     - ./backend/.env
  #   environment:
  #     REDIS_HOST: redis
  #     REDIS_PORT: 6379
  #     AUTH_SERVER_URL: http://auth-server:8081
  #   depends_on:
  #     - redis

  # redis:
  #   image: redis:7
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: core
      POSTGRES_PASSWORD: core
      POSTGRES_DB: core_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./main_module/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_net

  main_module:
    build: ./main_module
    env_file:
      - ./main_module/.env
    ports:
      - "18080:18080"
    depends_on:
      - postgres
    networks:
      - app_net

  auth:
    build: ./auth
    env_file:
      - ./auth/.env
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017
      GITHUB_CLIENT_ID: Ov23li4YURt6uH6rsHOL
      GITHUB_CLIENT_SECRET: fe15c95da6052b64f449dac3c716fd659f28e215
      YANDEX_CLIENT_ID: e99e48c417274cd4928c888ef31439c6
      YANDEX_CLIENT_SECRET: 468a8fcb30be408692f4579256e32d9e
      YANDEX_REDIRECT_URI: https://elda-unsimple-leandro.ngrok-free.dev/yandex/callback

    networks:
      - app_net

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app_net

  tg_nginx:
    image: nginx:latest
    volumes:
      - ./telegram_module/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"  
    depends_on:
      - bot_logic
    networks:
      - app_net

  tg_client:
    build: ./telegram_module/telegram_client
    env_file:
      - ./telegram_module/.env
    ports:
      - "8082:8082"
    networks:
      - app_net

  bot_logic:
    build: ./telegram_module/bot_logic
    ports:
      - "8083:8083"
    networks:
      - app_net

  tg_redis:
    image: redis:latest
    command: ["redis-server", "--requirepass", "--appendonly", "yes", "--port", "6380"]
    ports:
      - "6380:6380"
    networks:
      - app_net


networks:
  app_net:

volumes:
  pgdata:
  mongo-data: