FROM node:20

WORKDIR /app

# Устанавливаем зависимости
COPY package*.json ./
RUN npm install

# Копируем исходники
COPY . .

# Сборка TS (на будущее)
RUN npm run build

EXPOSE 8080

CMD ["npm", "run", "dev"]